### PR TITLE
warp fixes

### LINKED ISSUE #12: Time warp fails on short spectrogram
Hi, I have a question whether the time warping can sometimes cause a spectrogram to be too distorted or not. 

Screen Shot 2563-07-22 at 14 37 29

I applied Time Warping with W=2 and it sometimes results in ugly padding on the right side of the spectrogram. Is there any way to alleviate this problem?

### PR DESCRIPTION
**Pull request by PrathamSoni**
#12

### CODE REVIEW

**Comment by zcaceres** [comment]
Can you confirm this fixed your problem @keshawnhsieh ?

**Comment by zcaceres** [comment]
Why does this delete the SpecAugment notebook @PrathamSoni ?

**Comment by PrathamSoni** [comment]
@zcaceres I don't think it does...Perhaps you mean I should rerun the notebook contents?

**Comment by zcaceres** [comment]
Sorry @PrathamSoni, I misread. Sure if you want to re-run the notebook so it's in a readable state when it's first brought down from git that would be awesome.

**Comment by PrathamSoni** [comment]
@zcaceres Sorry for the delay, everything is updated, and it seems to be working :)

**Comment by zcaceres** [comment]
Thanks so much for doing this @PrathamSoni !

**Pull request merged**
